apiVersion: v1
kind: Service
metadata:
  labels:
    easytravel-tier: easytravel-frontend
    easytravel-type: angular
  name: easytravel-angular-frontend-service
  namespace: easytravel
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: web
    nodePort: 30081
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    easytravel-tier: easytravel-frontend
    easytravel-type: angular
  sessionAffinity: None
  type: NodePort
